In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

D:\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


### 第一題_算閏年：
請定義一個函式，讀進一個年份，輸出是不是閏年。

In [2]:
year = int(input('請輸入年份:'))
if (year%4==0 and year%100!=0) or year%400==0:
    print('這是閏年')
else:
    print('這不是閏年')

請輸入年份:2019
這不是閏年


### 第二題_請實作五乘五矩陣的矩陣加法函式：

In [8]:
m1 = np.random.randint(5,size=(5,5))
m2 = np.random.randint(5,size=(5,5))

def plus(m1,m2):
    return m1+m2

In [9]:
print(plus(m1,m2))

[[5 7 4 4 3]
 [3 0 0 5 4]
 [2 3 8 3 7]
 [8 7 7 3 3]
 [1 5 3 6 7]]


### 第三題_錄取分數表格

In [10]:
score = [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]
weight =[
[2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
[1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
[1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
[1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
[1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
[1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
[1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
[1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
[1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
]

In [16]:
subject=pd.DataFrame(weight,columns=['國文', '英文','數甲', '數乙', '物理', '化學', '生物', '歷史', '地理', '公民'],
                  index=['土語系','財政系','金融系','國貿系','會計系','法律系','公行系' ,'應數系','教育系'])

In [19]:
sum = np.dot(weight,score)
sum_table = pd.DataFrame(sum,columns=['加權分數'],index=['土語系','財政系','金融系','國貿系','會計系','法律系','公行系' ,'應數系','教育系'])
table = pd.concat([subject,sum_table],axis=1)
table

國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00  589.200
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00  350.350
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00  481.550
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00  642.450
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00  508.900
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25  436.975
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00  461.300
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00  570.075